### PR TITLE
convert to Swift 3 syntax

### PR DESCRIPTION
**Pull request by jonmadison**
make buildable out of the box (by Swift 3 compiler) by converting + adding SWIFT_VERSION to target

### CODE REVIEW

**Comment by jonmadison** [comment]
i'm guessing it'll fail tests because of the Swift version used in CI. I'll let you determine how best to handle:)

**Comment by mathmatrix828** [comment]
#30 fixes this much more cleanly by actually using Swift 3 syntax

**Comment by jonmadison** [comment]
what does "actually using Swift 3 syntax" mean

**Comment by mathmatrix828** [comment]
Instead of trying to tell CP to support legacy frameworks, just update the code to be compatible with Swift 3

**Pull request closed without merging**
